version: "3.8"
services:
  pg_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
    volumes:
      - /tmp/docker/pg_database:/tmp/pg_database
    ports:
      - "5432:5432"

  api:
    image: fastapi_lab
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
      DB_HOST: pg_database
      DB_PORT: 5432
    ports:
      - "8081:8081"
