version: "3.8"
services:
  pg_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
    volumes:
      - /tmp/docker/pg_database:/tmp/pg_database
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    image: fastapi_lab
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile_CRUD
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
      DB_HOST: pg_database
      DB_PORT: 5432
      REPORT_HOST: reports
      REPORT_PORT: 8082
    ports:
      - "8081:8081"

  reports:
    image: reports_lab
    restart: always
    build:
      context: ./reports
      dockerfile: Dockerfile_REPORTS
    environment:
      API_HOST: api
      API_PORT: 8081
